name: CI
on:
  push:
    branches: [main]
jobs:
  buid:
    name: GitOps Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: イメージをビルド
        run: |-
          DOCKER_BUILDKIT=1 docker image build . -f Dockerfile --tag ${{ secrets.DH_USERNAME }}/portfolio-t-dera:${{ github.run_number }}

      - name: イメージの脆弱性診断
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ secrets.DH_USERNAME }}/portfolio-t-dera:${{ github.run_number }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"

      - name: Docker Hubにログイン
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Docker Hubにイメージをプッシュ
        run: |-
          docker image push ${{ secrets.DH_USERNAME }}/portfolio-t-dera:${{ github.run_number }}

      - name: values.ymlを更新してconfigリポジトリにプルリクエストを作成する
        env:
          GIT_SSH_COMMAND: ssh -i ~/secret -o StrictHostKeyChecking=no -F /dev/null
        run: |-
          echo "${{ secrets.GH_SECRET_KEY }}" > ~/secret
          chmod 600 ~/secret

          git clone git@github.com:TOnodera/config-for-portfolio.t-dera.tokyo.git
          # update values.yaml in new branch
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.GH_USERNAME }}"
          git branch ci-robot/request-number-${{ github.run_number }}
          git checkout ci-robot/request-number-${{ github.run_number }}
          echo "${{ secrets.VALUES_YML }}" > ./values.yml
          sed -i 's/tag: [0-9]*/tag: ${{ github.run_number }}/g' values.yaml

          # git push
          git add values.yaml
          git commit -m "バージョンが更新されました: ${{ github.run_number }}"
          git push origin ci-robot/request-number-${{ github.run_number }}

          # create  pull request
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} > token.txt
          gh auth login --with-token < token.txt
          gh pr create --title 'Update Tag ${{ github.run_number }}' --body "Please Merge!!"
